<?php require_once('includes/conexion.php'); ?>
<?php include 'includes/header.php'; ?>

<div id="cont">
<h1>Introducci&oacute;n</h1>
<p>
  <!--El siguiente informe ser&aacute;  realizado en el marco de la materia Inform&aacute;tica Aplicada I del Instituto  Universitario Nacional del Arte. <br /> -->
  La finalidad del presente es poder explicitar  el objetivo central del proyecto &ldquo;Censo Interactivo 2010 Argentina&rdquo; demostrando  su importancia y relevancia en relaci&oacute;n a la visualizaci&oacute;n de datos como una  manera de interacci&oacute;n y representaci&oacute;n, en donde los usuarios pueden comprender  de forma visual una serie de datos complejos de manera m&aacute;s atractiva y eficaz.<br />
  Por  lo tanto, en principio partiremos exponiendo el objetivo del proyecto a ser  entregado explicando de qu&eacute; manera fue desarrollado el mismo y cu&aacute;l fue el  motivo de la elecci&oacute;n realizada. <br />
  Como  segunda medida, expondremos algunas de las conceptualizaciones que plantea  Lev Manovich acerca de la visualizaci&oacute;n de  datos tomando determinadas ideas puntuales de este, para  articularlas te&oacute;ricamente con el proyecto  realizado. Cabe destacar que si bien el desarrollo del informe girar&aacute; principalmente  en torno a  este autor, tambi&eacute;n se har&aacute;  menci&oacute;n de manera concreta a otro exponente llamado Friedman, lo que nos  permitir&aacute; fundamentar de una manera m&aacute;s profunda la elecci&oacute;n del proyecto a  entregar en la instancia de final.<br />
  Para  culminar, finalizaremos el informe propuesto por la materia realizando una breve  conclusi&oacute;n a modo de cierre en donde se puntualizaran brevemente las diversas  exposiciones elaboradas en relaci&oacute;n a la finalidad planteada promoviendo y  propiciando un mayor esclarecimiento del mismo. </p>

<h1>Desarrollo</h1>
<p>  Para  dar comienzo a la primera parte del desarrollo nos parece indispensable  plantear que el objetivo del proyecto a ser entregado  es el entendimiento y la interacci&oacute;n de los  usuarios a los resultados obtenidos en el Censo Nacional de Poblaciones,  Hogares y Viviendas realizado por el INDEC el 27 de Octubre del 2010 de una manera  visual y din&aacute;mica.<br />
  Este  fue desarrollado por medio de una aplicaci&oacute;n Web que interact&uacute;a con el usuario  y le indica los datos resultantes de las provincias que componen el Territorio  Argentino (1).  A su vez, el proyecto cuenta con un gr&aacute;fico de barras que   proporciona una segunda visualizaci&oacute;n  del total de habitantes, edad y sexo  (2). Como tercer propuesta, un grafico de barras que indica por sexo y edad los habitantes que utilizan computadoras en viviendas particulares (3).  Para la  producci&oacute;n del mismo se utilizaron los siguientes lenguajes de programaci&oacute;n: XHTML  - PHP - MYSQL- Processing.js. <br />
  El  motivo de la elecci&oacute;n realizada se debi&oacute; al inter&eacute;s que promovi&oacute; la magnitud de  datos resultantes del Censo Nacional de Poblaciones, Hogares y Viviendas 2010 plante&aacute;ndose  esto como un desaf&iacute;o que result&oacute; atractivo para ser llevado a cabo. <br />
  En  esta segunda parte del desarrollo nos centraremos principalmente en las conceptualizaciones  de Lev Manovich tanto como  de Friedman.<br />
  Como primera instancia  nos parece propicio señalar que Lev Manovich sostiene que la visualizaci&oacute;n de  datos es una de las formas culturales modernas y nuevas que los ordenadores han  hecho posible, ya que si bien en siglos anteriores era posible encontrar  ejemplos de representaci&oacute;n gr&aacute;fica de datos cuantitativos, estos eran m&aacute;s bien  una excepci&oacute;n mientras en la actualidad se han convertido en la norma. Tal es  as&iacute;, que hoy en d&iacute;a por medio del ordenador es posible crear visualizaciones din&aacute;micas,  introducir datos en tiempo real, observar conjuntos de datos muchos mayores  y basar la representaci&oacute;n gr&aacute;fica de datos en  su an&aacute;lisis matem&aacute;tico, utilizando m&eacute;todos variados para mapear un tipo de  representaci&oacute;n sobre otro.<br />
  En relaci&oacute;n a lo expuesto  hasta el momento podemos plantear que el proyecto realizado se enmarca en la  observaci&oacute;n de datos complejos y que por tanto el mismo se trata entonces  claramente de una visualizaci&oacute;n como sostiene el autor mencionado debido a que  en este existen datos cuantificados que no son visuales en s&iacute; mismos, sino que  se ven transformados en representaciones visuales.<br />
  Cabe destacar que como  sostiene Lev Manovich si bien el concepto de mapeado se parece mucho a la  visualizaci&oacute;n de datos la diferencia recae en que la visualizaci&oacute;n en si se  puede entender como un subconjunto particular del mapeado en el que una serie  de datos se mapea sobre una determinada imagen. Tal es as&iacute; que en el proyecto  presentado los datos generan una propia imagen en relaci&oacute;n a los resultados que  componen cada componente.<br />
  Por otro lado, es  indispensable plantear que dicho autor expone que la visualizaci&oacute;n de datos da  lugar a posibles variaciones de im&aacute;genes infinitas como se observa en nuestro  trabajo. Es decir,  siguiendo a Lev  Manovich podr&iacute;amos plantear que en el mismo se produce una reducci&oacute;n de datos  cuantitativos a sus patrones y estructuras. No obstante, estas luego explotan  en diferentes im&aacute;genes visuales ricas y concretas.<br />
  Por &uacute;ltimo, nos parece  pertinente afirmar que como plantea Friedman el objetivo principal de visualizaci&oacute;n de datos es comunicar  informaci&oacute;n clara y eficaz a trav&eacute;s de medios gr&aacute;ficos por lo tanto podemos  plantear a modo de hip&oacute;tesis que nuestro proyecto cumple con dicho objetivo ya  que a trav&eacute;s del mismo se comunica variada informaci&oacute;n sobre los datos  obtenidos en el Censo Nacional  sin caer en  una est&eacute;tica y funcionalidad t&iacute;pica que resulte mon&oacute;tona, demostrando diversos  datos complejos de una manera m&aacute;s intuitiva que promueva un mayor entendimiento  y atenci&oacute;n por parte del usuario.</p>


<h1>Conclusi&oacute;n</h1>
 <p> A modo de cierre, nos  parece propicio hacer algunos comentarios finales sobre los temas planteados en  este informe para llegar a una mejor conclusi&oacute;n y esclarecimiento de los conceptos  vinculados en el mismo dando una opini&oacute;n personal del trabajo realizado. <br />
  Por  un lado nos parece importante aclarar que los conceptos de  Lev Manovich tanto como los de Friedman, nos  han sido de mucha ayuda para realizar  el  informe propuesto por la c&aacute;tedra, ya que en ning&uacute;n momento hemos sentido la  necesidad de forzar alg&uacute;n concepto para poder explicar el proyecto presentado,  sino que por el contrario nos hemos sentido en comodidad con los mismos. <br />
  Por  otro lado, quisi&eacute;ramos sostener que desde nuestra perspectiva el objetivo  propuesto para el &ldquo;Censo Interactivo 2010 Argentina&rdquo; se ha podido concretar ya  que al finalizar el mismo hemos sentido que este no solo promueve la  interacci&oacute;n de los usuarios con los resultados obtenidos por el Censo Nacional  de Poblaciones, Hogares y Viviendas realizado por el INDEC el 27 de Octubre del  2010 de manera no convencional, sino que adem&aacute;s proporciona una manera  diferente de poder comunicar dicha informaci&oacute;n de forma moderna. <br />
  Es  decir, creemos que la manera de presentar estos datos complejos ha sido exitosa  ya que al ser propuestos en un formato diferente generan que el usuario tenga  una mayor comprensi&oacute;n de los mismos, y que a nivel perceptivo se interese m&aacute;s  por aquello que visualiza, pudiendo establecer una relaci&oacute;n din&aacute;mica, creativa  y funcional con aquello que le es brindado.<br />
  Antes de finalizar es  imprescindible plantear que los datos utilizados en el proyecto presentado son  una muestra del Censo Nacional 2010 debido a que por cuestiones de extensi&oacute;n  nos pareci&oacute; m&aacute;s propicio hacer un recorte de los mismos.<br />
  Concluyendo, el proyecto  propuesto trata de presentar de forma  visual  y personalizada un conjunto  de  informaci&oacute;n de manera que resulte de  f&aacute;cil compresi&oacute;n al usuario. Esto genera una atracci&oacute;n hacia aquello que  visualiza lo cual fomenta la participaci&oacute;n del mismo promoviendo un  acercamiento real a las nuevas formas culturales modernas de nuestro siglo.</p>

<h1>Anexo:</h1>
<p>(1)El mapa interactuar con el usuario brindándole información sobre la provincia elegida; La dimensión y el color de los círculos hacen referencia al tipo de dato.</p>
<img class="map" src="images/map1.jpg" alt="map1" width="800" height="300"/>
<p>(2)Grafico de barras donde se observa la totalidad de habitantes por edad y sexo.</p>
<img class="map" src="images/map2.jpg" alt="map1" width="800" height="300"/>
<p>(2)Grafico de barras donde se observa la utilización de computadoras en viviendas particulares por sexo y edad</p>
<img class="map" src="images/map3.jpg" alt="map1" width="800" height="300"/>

<h1>Bibliograf&iacute;a</h1>
<p> Manovich, Lev <em>&ldquo;La visualizaci&oacute;n de datos como abstracci&oacute;n y antisublime&rdquo; </em>en  Estudios Visuales</p>
<p>- Friedman, Vitaly (2008)&nbsp;
<a href="http://www.smashingmagazine.com/2008/01/14/monday-inspiration-data-visualization-and-infographics/"><em>&quot;La  visualizaci&oacute;n de datos y la infograf&iacute;a&quot;</em></a>&nbsp;en Gr&aacute;ficos,  la inspiraci&oacute;n Lunes, 14 de enero 2008.</p>
<p>- Censo Nacional de Poblaciones,  Hogares y Viviendas 2010</p>
</div>  

<?php include 'includes/footer.php'; ?>

